### ISSUE TITLE
how to config yeticss in webpack 2?

### ISSUE THREAD

**Issue by Jinnified** [andyet/yeti.css#106]
so this 
```
stylus: {
    use: [yeticss()]
  }
```

wont work in webpack 2, anyone can help?

**Comment by latentflip** [comment]
Yeticss is just a stylus plugin, so this will probably cover it: https://github.com/shama/stylus-loader#webpack-2

**Comment by latentflip** [comment]
Added a note in the readme https://github.com/andyet/yeti.css/commit/2d260969b9bec0e7c6b2ab41a56673802cffd59a
