### ISSUE TITLE
Improve installation, setup, and configuration instructions

### ISSUE THREAD

**Issue by adambrault** [andyet/yeti.css#46]
```
> npm i --save-dev yeticss
```

...installed successfully

```
> stylus -u yeticss ./public/css/main.styl
```

gives me

```
Error: Cannot find module 'yeticss'
```

**Comment by HenrikJoreteg** [comment]
Here's how I've been setting everything up, which includes yeti-css: https://github.com/henrikjoreteg/hjs-webpack

**Comment by HenrikJoreteg** [comment]
Definitely think it'd be nice to have a "how to use" section that made it a bit easier to spin up.
