### ISSUE TITLE
Does the information about deploy keys still true if yeti.css is on public npm?

### ISSUE THREAD

**Issue by thefoxis** [andyet/yeti.css#65]
Since I'm about to publish yeti.css on npm and I'm trying to update the documentation&mdash;is this still relevant? Seems to me that it's not but I don't want to jump the :dolphin: here.

> Because this is an npm module, but isn't on npm, management of it is a little tricker.
> Deployment: If you are deploying your app, Bear will also need to setup deploy keys for the andyet/yeticss repo, so that npm can grab yeticss from the private repo. This is why you should use "git+ssh://git@github.com/andyet/yeticss" in your package.json to reference yeticss.

**Comment by bear** [comment]
If the module is being published to NPM then all of that talk about keys can go away.

**Comment by thefoxis** [comment]
Thank you!
