### ISSUE TITLE
Incorrect markup for buttons

### ISSUE THREAD

**Issue by designsaves** [andyet/yeti.css#68]
On yeticss.com, the markup for several of the buttons styles says `href` where I believe it should say `class`.

![screen shot 2015-01-28 at 3 08 52 pm](https://cloud.githubusercontent.com/assets/4055156/5949165/d9d75990-a6ff-11e4-9242-b073646ab841.png)

**Comment by thefoxis** [comment]
@meetthelegend can you please assign the issues so I can actually know when they're opened? thanks.
