### ISSUE TITLE
Consistent heights for buttons

### ISSUE THREAD

**Issue by designsaves** [andyet/yeti.css#76]
It would be great if the solid and outlined buttons had consistent heights, so that they look nice when they appear inline.

![screen shot 2015-05-01 at 9 50 20 pm](https://cloud.githubusercontent.com/assets/4055156/7439955/1c3ce7ce-f04c-11e4-8d40-6c09f15cfee9.png)

**Comment by thefoxis** [comment]
Good point @meetthelegend; thanks!
