### ISSUE TITLE
Button animation on load

### ISSUE THREAD

**Issue by adamavenir** [andyet/yeti.css#84]
I have seen this when using yeti.css before and I don't know what's caused it.

![](https://cldup.com/28o1qplBaJ.gif)

It seems to be animating from the browser default state of these elements to the yeti.css style.

Is this a bug in yeti.css or is there something different that should be done to prevent this?

**Comment by latentflip** [comment]
Looks like browsers are weird, and this can happen even on the simplest sites based on weird conditions (http://stackoverflow.com/questions/14389566/stop-css3-transition-from-firing-on-page-load)

Proposed fix (though requires js: https://css-tricks.com/transitions-only-after-page-load/)
