### ISSUE TITLE
How to get breakpoints working?

### ISSUE THREAD

**Issue by bclinkinbeard** [andyet/yeti.css#87]
I'm including the styles in my stylus via `@import 'yeticss'`, and mimicking the DOM structure from yeticss.com, but when I view my page on mobile, the breakpoints aren't working. The text is small, doesn't fill the viewport, etc.

Is there something special I need to do that I'm missing?

My DOM:

``` html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>My Killer Post</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <header role="banner">
    <div class="container">
      <h1>My Killer Post</h1>
    </div>
  </header>
  <div class="container">
    <section><p>This is a sweet blawg post. It has <strong>bold</strong> text and <em>italics</em>.     </p>
    <h2 id="subheader">Subheader</h2>
    <p>Oooh, yea. Maybe some JavaScript?</p>
    <p>Wow!</p>
  </section>
</div>
</body>
</html>
```

**Comment by latentflip** [comment]
Hey Ben, you're missing the viewport meta tag:

```
<meta name="viewport" content="width=device-width, initial-scale=1">
```

More details here: https://css-tricks.com/snippets/html/responsive-meta-tag/

**Comment by bclinkinbeard** [comment]
Ah ha, thanks, Philip!
